import Head from 'next/head';
import Homepage from './Homepage';

export default function Home({ projects }) {
	return (
		<>
			<Head>
				<title>Sam Adjei | Web Developer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="bg-background">
				<div className="container mx-auto px-8 md:px-14 lg:px-24 py-6 w-full">
					<Homepage />
				</div>
			</main>
		</>
	);
}

